// state products
export const GET_PRODUCTS_RIGHT='GET_PRODUCTS_RIGHT';

// state pedido
export const SELECT_PRODUCT='SELECT_PRODUCT';
export const CONFIRM_ORDER_PRODUCT='CONFIRM_ORDER_PRODUCT';
export const DISPLAYRESUMEN='DISPLAYRESUMEN';
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const DELIVERY_ORDER='DELIVERY_ORDER';